name: guesstheword
version: 1.1.2
summary: Guess The Word
description: Another take on classic hangman guess the word game.

confinement: strict
base: core22
grade: stable
icon: snap/gui/guesstheword.png

apps:
  guesstheword:
    command: desktop-launch $SNAP/usr/bin/guesstheword
    desktop: snap/gui/guesstheword.desktop
    plugs:
      - desktop

parts:
  guesstheword:
    plugin: dump
    source: build/linux/x64/release/bundle
