name: guesstheword
version: 1.1.2
summary: Guess The Word
description: Another take on classic hangman guess the word game.

confinement: strict
base: core22
grade: stable
icon: snap/gui/guesstheword.png

apps:
  guesstheword:
    command: desktop-launch $SNAP/usr/bin/guesstheword
    desktop: guesstheword.desktop
    plugs:
      - desktop

parts:
  guesstheword:
    plugin: flutter
    flutter-target: lib/main.dart
    source: .
    build-packages:
      - libgtk-3-dev
      - pkg-config
      - libunwind-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev