name: guesstheword
version: 1.1.2
summary: Guess The Word
description: Another take on classic hangman guess the word game.

confinement: strict
base: core22
grade: stable
icon: gui/guesstheword.png

apps:
  guesstheword:
    command: desktop-launch $SNAP/usr/bin/guesstheword
    desktop: guesstheword.desktop
    plugs:
      - desktop

parts:
  guesstheword:
    plugin: flutter
    flutter-target: ../lib/main.dart
    source: ..