# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - "!main"

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions:
  contents: write

jobs:
  build-web-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Web and Android
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
        architecture: x64
    - run: flutter pub get
    - run: flutter build web --base-href /flutter-guesstheword/
    - run: flutter build apk --release

    - name: Attach Website
      uses: actions/upload-artifact@v3
      with:
        name: Web-guesstheword-${{ github.ref_name }}-${{ github.sha }}
        path: build/web

    - name: Attach APK
      uses: actions/upload-artifact@v3
      with:
        name: APK-guesstheword-${{ github.ref_name }}-${{ github.sha }}
        path: build/app/outputs/flutter-apk/app-release.apk

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install flutter dependencies
      run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-0 libgtk-3-dev libblkid1 liblzma5

    - name: Install app dependencies
      run: sudo apt-get install -y -f libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev

    - name: Build Linux
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
        architecture: x64
    - run: flutter pub get
    - run: flutter config --enable-linux-desktop
    - run: flutter build linux --release

    - name: Attach Linux Bundle
      uses: actions/upload-artifact@v3
      with:
        name: Linux-guesstheword-${{ github.ref_name }}-${{ github.sha }}
        path: build/linux/x64/release/bundle

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Windows
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.13.8'
        architecture: x64
    - run: flutter pub get
    - run: flutter config --enable-windows-desktop
    - run: flutter build windows --release

    - name: Attach Windows Bundle
      uses: actions/upload-artifact@v3
      with:
        name: Win-guesstheword-${{ github.ref_name }}-${{ github.sha }}
        path: build/windows/runner/Release

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Macos
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
        architecture: x64
    - run: flutter pub get
    - run: flutter config --enable-macos-desktop
    - run: flutter build macos --release

    - name: Attach Windows Bundle
      uses: actions/upload-artifact@v3
      with:
        name: Mac-guesstheword-${{ github.ref_name }}-${{ github.sha }}
        path: build/macos/Build/Products/Release
