# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "!main"

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Environment Variables
      shell: bash
      run: |
        echo "::set-output name=branch::$(echo ${GITHUB_REF////-} | sed s/refs-heads-//)"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      id: vars

    - name: Build Web and Android
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
    - run: flutter pub get
    - run: flutter build web --base-href /flutter-guesstheword/
    - run: flutter build apk --release

    - name: Upload Website
      uses: actions/upload-artifact@v3
      with:
        name: Web-guesstheword-${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}.zip
        path: build/web

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: APK-guesstheword-${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}.zip
        path: build/app/outputs/flutter-apk/app-release.apk
