name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            Web version deployed at https://alleey.github.io/flutter-guesstheword/#/
          draft: true
          prerelease: false

  build-web-android:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
    - uses: actions/checkout@v4

    - name: Build
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
        architecture: x64
    - run: flutter pub get
    - run: flutter build web --base-href /flutter-guesstheword/
    - run: flutter build apk --release

    - name: Deploy Web
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build/web

    - name: Archive Web Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: guesstheword-v${{ github.run_number }}-web.zip
        directory: build/web

    - name: Attach Web Bundle
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: build/web/guesstheword-v${{ github.run_number }}-web.zip
        asset_name: guesstheword-v${{ github.run_number }}-web.zip
        asset_content_type: application/zip

    - name: Attach APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: guesstheword-v${{ github.run_number }}.apk
        asset_content_type: application/zip

  build-linux:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
    - uses: actions/checkout@v4

    - name: Install flutter dependencies
      run: sudo apt-get install -y -f clang cmake ninja-build libgtk-3-dev

    - name: Install app dependencies
      run: sudo apt-get install -y -f libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev

    - name: Build
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
        architecture: x64
    - run: flutter pub get
    - run: flutter config --enable-linux-desktop
    - run: flutter build linux --release

    - name: Archive Linux Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: guesstheword-v${{ github.run_number }}-linux.zip
        directory: build/linux/x64/release/bundle

    - name: Attach Linux Bundle
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: build/linux/x64/release/bundle/guesstheword-v${{ github.run_number }}-linux.zip
        asset_name: guesstheword-v${{ github.run_number }}-linux.zip
        asset_content_type: application/zip

  build-windows:
    runs-on: windows-latest
    needs: [release]
    steps:
    - uses: actions/checkout@v4

    - name: Build
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.19.5'
        architecture: x64
    - run: flutter pub get
    - run: flutter config --enable-windows-desktop
    - run: flutter build windows --release

    - name: Archive Windows Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: guesstheword-v${{ github.run_number }}-windows.zip
        directory: build/windows/x64/runner/Release

    - name: Attach Windows Bundle
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: build/windows/x64/runner/Release/guesstheword-v${{ github.run_number }}-windows.zip
        asset_name: guesstheword-v${{ github.run_number }}-windows.zip
        asset_content_type: application/zip

  build-macos:
    runs-on: macos-latest
    needs: [release]
    steps:
    - uses: actions/checkout@v4

    - name: Build
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
        architecture: x64
    - run: flutter pub get
    - run: flutter config --enable-macos-desktop
    - run: flutter build macos --release

    - name: Archive Macos Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: guesstheword-v${{ github.run_number }}-macos.zip
        directory: build/macos/Build/Products/Release

    - name: Attach Macos Bundle
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: build/macos/Build/Products/Release/guesstheword-v${{ github.run_number }}-macos.zip
        asset_name: guesstheword-v${{ github.run_number }}-macos.zip
        asset_content_type: application/zip
